"""empty message

Revision ID: 447c67febcff
Revises: 2ed7340b38e8
Create Date: 2025-10-29 14:41:14.780984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '447c67febcff'
down_revision: Union[str, Sequence[str], None] = '2ed7340b38e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
