"""empty message

Revision ID: 4d39333b572a
Revises: cce1b9185247
Create Date: 2025-10-29 10:54:33.099711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4d39333b572a'
down_revision: Union[str, Sequence[str], None] = 'cce1b9185247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
